config/routes.rb
  resources :apis

  post 'open_new_store' => 'apis#open_new_store', :as => :open_new_store
  get 'seach_from_mobile' => 'apis#seach_from_mobile', :as => :seach_from_mobile
  post 'send_to_web' => 'apis#send_to_web', :as => 'send_to_web'
  get 'seller_buyer_conversation' => 'apis#seller_buyer_conversation', :as => :seller_buyer_conversation
  get 'set_order_status_by_seller' => 'apis#set_order_status_by_seller', :as => :set_order_status_by_seller
  get 'view_shop_licensce' => 'apis#view_shop_licensce', :as => :view_shop_licensce
  get 'order_view_by_seller' => 'apis#order_view_by_seller', :as => :order_view_by_seller
  get 'store_detail_view_by_seller' => 'apis#store_detail_view_by_seller', :as => :store_detail_view_by_seller
  get 'store_detail_view_by_buyer' => 'apis#store_detail_view_by_buyer', :as => :store_detail_view_by_buyer

  get 'my_product_order_list' => 'apis#my_product_order_list', :as => :my_product_order_list
  post 'edit_my_store' => 'apis#edit_my_store', :as => :edit_my_store
  post 'edit_my_product' => 'apis#edit_my_product', :as => :edit_my_product
  get 'order_confirm_list' => 'apis#order_confirm_list', :as => :order_confirm_list
  get 'order_delivery_list' => 'apis#order_delivery_list', :as => :order_delivery_list
  get 'order_completed_list' => 'apis#order_completed_list', :as => :order_completed_list
  get 'order_rejected_list' => 'apis#order_rejected_list', :as => :order_rejected_list
  get 'order_processing_list' => 'apis#order_processing_list', :as => :order_processing_list

  post 'to_send_shipment' => 'apis#to_send_shipment', :as => :to_send_shipment
  get 'store_desc' => 'apis#store_desc', :as => :store_desc
  get 'last_three_json' => 'apis#last_three_json', :as => :last_three_json

  get 'get_store_product' => "apis#get_store_product", :as => :get_store_product
  get 'get_store_product_by_seller' => "apis#get_store_product_by_seller", :as => :get_store_product_by_seller

  post 'to_send_rating' => "apis#to_send_rating", :as => :to_send_rating
  get 'get_rating' => "apis#get_rating", :as => :get_rating

  get 'test_json' => 'apis#test_json', :as => :test_json
  get 'my_big_deals' => 'apis#my_big_deals', :as => :my_big_deals
  get 'my_api_services' => 'apis#my_api_services', :as => :my_api_services
  get 'my_api_training_and_schools' => 'apis#my_api_training_and_schools', :as => :my_api_training_and_schools
  get 'my_api_sports' => 'apis#my_api_sports', :as => :my_api_sports
  get 'my_api_toys' => 'apis#my_api_toys', :as => :my_api_toys
  get 'my_api_gifts' => 'apis#my_api_gifts', :as => :my_api_gifts
  get 'my_api_car_accessories' => 'apis#my_api_car_accessories', :as => :my_api_car_accessories
  get 'my_api_motorcycle_accessories' => 'apis#my_api_motorcycle_accessories', :as => :my_api_motorcycle_accessories
  get 'my_api_machines' => 'apis#my_api_machines', :as => :my_api_machines
  get 'my_api_instruments' => 'apis#my_api_instruments', :as => :my_api_instruments
  get 'my_api_equipment' => 'apis#my_api_equipment', :as => :my_api_equipment
  get 'my_api_bath_supplies' => 'apis#my_api_bath_supplies', :as => :my_api_bath_supplies
  get 'my_api_makeup_and_skincares' => 'apis#my_api_makeup_and_skincares', :as => :my_api_makeup_and_skincares
  get 'my_api_beauty_equipments' => 'apis#my_api_beauty_equipments', :as => :my_api_beauty_equipments
  get 'my_api_medicines' => 'apis#my_api_medicines', :as => :my_api_medicines
  get 'my_api_home_appliances' => 'apis#my_api_home_appliances', :as => :my_api_home_appliances
  get 'my_api_computers' => 'apis#my_api_computers', :as => :my_api_computers
  get 'my_api_telephone_accessories' => 'apis#my_api_telephone_accessories', :as => :my_api_telephone_accessories
  get 'my_api_electrical_equipments' => 'apis#my_api_electrical_equipments', :as => :my_api_electrical_equipments
  get 'my_api_fashion_hats' => 'apis#my_api_fashion_hats', :as => :my_api_fashion_hats
  get 'my_api_fashion_footwears' => 'apis#my_api_fashion_footwears', :as => :my_api_fashion_footwears
  get 'my_api_fashion_bags' => 'apis#my_api_fashion_bags', :as => :my_api_fashion_bags
  get 'my_api_fashion_accessories' => 'apis#my_api_fashion_accessories', :as => :my_api_fashion_accessories
  get 'my_api_fashion_clothings' => 'apis#my_api_fashion_clothings', :as => :my_api_fashion_clothings
  get 'my_api_stores' => 'apis#my_api_stores', :as => :my_api_stores
  post 'get_ip' => 'apis#get_ip', :as => :get_ip

  

  resources :services
  resources :training_and_schools
  resources :sports
  resources :toys
  resources :gifts
  resources :car_accessories
  resources :motorcycle_accessories
  resources :machines
  resources :instruments
  resources :equipment
  resources :bath_supplies
  resources :makeup_and_skincares
  resources :beauty_equipments
  resources :medicines
  resources :home_appliances
  resources :computers
  resources :telephone_accessories
  resources :telephone_accessories
  resources :electrical_equipments
  resources :fashion_hats
  resources :fashion_footwears
  resources :fashion_bags
  resources :fashion_accessories
  resources :fashion_clothings
  resources :carts
  get 'add_to_cart' => 'carts#_cart'

  resources :line_items
  get 'my_items' => 'line_items#my_items'
  

  resources :orders
  get 'my_order' => 'orders#my_order'
  get 'my_order_status' => 'orders#my_order_status'

  resources :products
  get 'my_product' => 'products#my_product', :as => :my_product
  get 'my_products' => 'products#my_products', :as => :my_products
  get 'my_sell_product' => 'products#my_sell_product', :as => :my_sell_product
  get 'set_as_bigdeal/:id' => 'products#set_as_bigdeal', :as => :set_as_bigdeal
  

  resources :stores
  get 'dashboard' => 'stores#dashboard', :as => :dashboard

  resources :fashions
  resources :fronts

  get "big_deals" => "fronts#big_deals", :as => :big_deals  

  get "products_by_category" => "fronts#products_by_category", :as => :products_by_category
  get "apply_as_seller/:id" => "fronts#apply_as_seller", :as => :apply_as_seller
  get "unauthorized" => "fronts#unauthorized", :as => :unauthorized
  get "send_to_pusher" => "fronts#send_to_pusher", :as => :send_to_pusher
  get "add_to_favourite" => "fronts#add_to_favourite", :as => :add_to_favourite
  get "search_result" => "fronts#search_result", :as => :search_result
  root 'fronts#home'

 get 'home' => 'fronts#home'
 get 'about' => 'fronts#about'
 get 'cart' => 'fronts#cart'
 get 'category' => 'fronts#category'
 get 'category_list' => 'fronts#category_list'
 get 'compare' => 'fronts#compare'
 get 'contact' => 'fronts#contact'
 get 'login' => 'fronts#login'
 get 'product' => 'fronts#product'
 get 'product_full' => 'fronts#product_full' , :as => :product_full
 get 'mobile_product_detail' => 'fronts#mobile_product_detail' , :as => :mobile_product_detail

 get 'register' => 'fronts#register'
 get 'check_out' => 'fronts#check_out'
 get 'thanks_you' => 'fronts#thanks_you'
 get 'check_out_as_guest' => 'fronts#check_out_as_guest'
 get 'product_by_category' => 'fronts#product_by_category'
 get 'my_conversation' => 'fronts#my_conversation'
 
 

 get 'fashion_related' => 'fronts#fashion_related', :as => :fashion_related
 get 'electronics_related' => 'fronts#electronics_related', :as => :electronics_related
 get 'health_beauty_related' => 'fronts#health_beauty_related', :as => :health_beauty_related
 get 'industrial_part' => 'fronts#industrial_part', :as => :industrial_part
 get 'auto_transportation' => 'fronts#auto_transportation', :as => :auto_transportation
 get 'sports_related' => 'fronts#sports_related', :as => :sports_related
 get 'service_related' => 'fronts#service_related', :as => :service_related

 get 'product_bath_supplies' => 'bath_supplies#product_bath_supplies', :as => :product_bath_supplies
  
 get 'product_beauty_equipments' => 'beauty_equipments#product_beauty_equipments', :as => :product_beauty_equipments
   
 get 'product_car_accessories' => 'car_accessories#product_car_accessories', :as => :product_car_accessories
    
 get 'product_computers' => 'computers#product_computers', :as => :product_computers
 
 get 'product_electrical_equipments' => 'electrical_equipments#product_electrical_equipments', :as => :product_electrical_equipments

 get 'product_equipments' => 'equipment#product_equipments', :as => :product_equipments

 get 'product_fashion_accessories' => 'fashion_accessories#product_fashion_accessories', :as => :product_fashion_accessories

 get 'product_fashion_bags' => 'fashion_bags#product_fashion_bags', :as => :product_fashion_bags

 get 'product_fashion_clothings' => 'fashion_clothings#product_fashion_clothings', :as => :product_fashion_clothings

 get 'product_fashion_footwears' => 'fashion_footwears#product_fashion_footwears', :as => :product_fashion_footwears

 get 'product_fashion_hats' => 'fashion_hats#product_fashion_hats', :as => :product_fashion_hats
   
 get 'product_gifts' => 'gifts#product_gifts', :as => :product_gifts

 get 'product_home_appliances' => 'home_appliances#product_home_appliances', :as => :product_home_appliances
  
 get 'product_instruments' => 'instruments#product_instruments', :as => :product_instruments

 get 'product_machines' => 'machines#product_machines', :as => :product_machines
  
 get 'product_makeup_and_skincares' => 'makeup_and_skincares#product_makeup_and_skincares', :as => :product_makeup_and_skincares
   
 get 'product_medicines' => 'medicines#product_medicines', :as => :product_medicines
 
 get 'product_motorcycle_accessories' => 'motorcycle_accessories#product_motorcycle_accessories', :as => :product_motorcycle_accessories
  
 get 'product_services' => 'services#product_services', :as => :product_services
  
 get 'product_sports' => 'sports#product_sports', :as => :product_sports
 
 get 'product_telephone_accessories' => 'telephone_accessories#product_telephone_accessories', :as => :product_telephone_accessories

 get 'product_toys' => 'toys#product_toys', :as => :product_toys
  

app/models/medicine.rb
class Medicine < ActiveRecord::Base

  after_create :add_to_product

  has_attached_file :avatar1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar1, content_type: /\Aimage\/.*\Z/

  has_attached_file :avatar2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar2, content_type: /\Aimage\/.*\Z/
  
  has_attached_file :avatar3, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar3, content_type: /\Aimage\/.*\Z/
  
  has_attached_file :avatar4, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar4, content_type: /\Aimage\/.*\Z/
  
  has_attached_file :avatar5, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar5, content_type: /\Aimage\/.*\Z/

    DELIVERY = ["self_delivery", "transporter_logistics"]

 def add_to_product

      
     raw_seller_name = User.where(:id => self.user_id).pluck(:name)
     @config_seller = raw_seller_name.to_s.gsub('["', '')
     @seller_name = @config_seller.to_s.gsub('"]', '')

     
      Product.create( :mmdealer_code => "medicines"+(Product.maximum(:id).next.to_i).to_s,:user_id => self.user_id,
      :seller_name => @seller_name,
      :title => self.title,
      :ingredient => self.ingredient,
      :usage => self.usage,
      :made_by_country => self.made_by_country,
      :description => self.description,
      :certification => self.certification,
      :price => self.price,
           :store_name => self.store_name,
      :category => "medicines",
      :avatar1_file_name => self.avatar1.url,
      :avatar2_file_name => self.avatar2.url,
      :delivery_category => self.delivery_category,
      :avatar3_file_name => self.avatar3.url,
      :avatar4_file_name => self.avatar4.url,
      :avatar5_file_name => self.avatar5.url,
            :avatar1_edit => self.avatar1_edit,
      :avatar2_edit => self.avatar2_edit,
      :avatar3_edit => self.avatar3_edit,
      :avatar4_edit => self.avatar4_edit,
      :avatar5_edit => self.avatar5_edit,
      :avatar6_edit => self.avatar6_edit,
      :avatar7_edit => self.avatar7_edit,
      :avatar8_edit => self.avatar8_edit,
      :caution => self.caution)
  end
  
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]
   layout :layout_per_action
     before_action :authenticate_user!, only: [:new]
  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  def product_medicines
      @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
       @store_name = Store.where(:user_id => current_user).pluck(:store_name)
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to my_products_path, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:delivery_category,:avatar5_edit,:avatar6_edit,:avatar7_edit,:avatar8_edit,:avatar1_edit,:avatar2_edit,:avatar3_edit,:avatar4_edit,:quantity,:store_name,:user_id,:price,:avatar1,:avatar2,:avatar3,:avatar4,:avatar5,:title, :category, :certification, :ingredient, :usage, :made_by_country, :description, :caution)
    end

    def layout_per_action
      if action_name == "index" or "product_medicines" 
           "application"
      else
        "backend"
      end
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
  <div class="col-md-6"> 

    <div class="panel panel-default">
        <div class="panel-body">
            <h4>New  Medicine</h4>
            <hr/>


<%= form_for(@medicine, html: { multipart: true }) do |f| %>
              <% if @medicine.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this product from being saved:</h2>

                  <ul>
                  <% @medicine.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>



      <%= f.text_field :store_name, :value => @store_name, :style => "display:none;" %>
            <div class="form-group" >
              <%= f.label :delivery_category %>
              <%= f.select(:delivery_category, Medicine::DELIVERY) %>
            </div>



             <div class="form-group" style="display:none;">
              <%= f.label :user_id %>
              <%= f.number_field :user_id, :value => current_user.id %>
            </div>

            <div class="form-group">
              <%= f.label :title %><br/>
              <%= f.text_field :title, :class=>"form-control", :required => true  %>
            </div>

            <div class="form-group">
              <%= f.label :certification %><br/>
              <%= f.text_field :certification, :class=>"form-control" , :required => true %>
            </div>

            <div class="form-group">
              <%= f.label :ingredient %><br/>
              <%= f.text_field :ingredient, :class=>"form-control", :required => true  %>
            </div>

                

            <div class="form-group">
              <%= f.label :made_by_country %><br/>
              <%= f.text_field :made_by_country, :class=>"form-control", :required => true  %>
            </div>


            <div class="form-group">
              <%= f.label :usage %><br/>
              <%= f.text_area :usage, :class=>"form-control", :rows => 20  %>
            </div>






            


        </div>
    </div> 
  
  </div>
  <div class="col-md-6">

    <div class="panel panel-default">
        <div class="panel-body">
         <h4>Product Images (Width:250px High:200px for best view)</h4>
            <hr/>
      
            <!-- crop mage -->
               <div class="col-md-6">
                      <div class="image-editor1">

                          <%= f.file_field :avatar1, :class=>"cropit-image-input" %>
                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar1_edit, :class=>"form-control", :style=>"display:none"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav1">


                  
                          

                        </div>
              </div>
               <div class="col-md-6">
                      <div class="image-editor2">

                          <%= f.file_field :avatar2, :class=>"cropit-image-input" %>
                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar2_edit, :class=>"form-control", :style=>"display:none"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav2">


                  
                       

                        </div>
              </div>


                  <div class="col-md-6">
                      <div class="image-editor3">

                          <%= f.file_field :avatar3, :class=>"cropit-image-input" %>
                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar3_edit, :class=>"form-control", :style=>"display:none"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav3">


                  
                       

                        </div>
              </div>



    <div class="col-md-6">
                      <div class="image-editor4">

                          <%= f.file_field :avatar4, :class=>"cropit-image-input" %>
                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar4_edit, :class=>"form-control", :style=>"display:none"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav4">


                  
                       

                        </div>
              </div>

           
                   <div class="form-group">
              <%= f.label :description %><br/>
              <%= f.text_area :description, :class=>"form-control", :rows => 10  %>
            </div>

                   <div class="form-group">
              <%= f.label :caution %><br/>
              <%= f.text_area :caution, :class=>"form-control", :rows => 10  %>
            </div>

            
        </div>
    </div>


  </div>

  <div class="col-md-12">

    <div class="panel panel-default">
        <div class="panel-body">


   <div class="col-md-3">
                      <div class="image-editor5">

                            <input type="file"  class="cropit-image-input">

                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar5_edit, :class=>"form-control", :style => "display:none;"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav5">


                  
                       

                        </div>
    </div>

       <div class="col-md-3">
                      <div class="image-editor6">

                            <input type="file"  class="cropit-image-input">

                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar6_edit, :class=>"form-control", :style => "display:none;"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav6">


                  
                       

                        </div>
    </div>


       <div class="col-md-3">
                      <div class="image-editor7">

                            <input type="file"  class="cropit-image-input">

                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar7_edit, :class=>"form-control", :style => "display:none;"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav7">


                  
                       

                        </div>
    </div>


       <div class="col-md-3">
                      <div class="image-editor8">

                            <input type="file"  class="cropit-image-input">

                          <div class="cropit-preview"></div>
                          <div class="image-size-label">
                            Resize image
                          </div>

                           <%= f.text_field :avatar8_edit, :class=>"form-control", :style => "display:none;"  %>


                            <input type="range" class="cropit-image-zoom-input" id="exportav8">


                  
                       

                        </div>
    </div>

    
                        </div>
    </div>


</div>

  <div class="col-md-12">

    <div class="panel panel-default">
        <div class="panel-body">

           <div class="actions">
            Please enter "Create" button to upload your
            medicine product in your store.
            <span style="float:right;"><%= f.submit %></span>
          </div>

        </div>
    </div>
  </div>


<% end %>



    <script>
      $(function() {
        $('.image-editor1').cropit({

     minZoom: 'fit',
    imageState: {
            src: 'http://localhost:3000/',
          },
        });

        $('.image-editor2').cropit({

     minZoom: 'fit',
    imageState: {
            src: 'http://localhost:3000/',
          },
        });


        $('.image-editor3').cropit({

     minZoom: 'fit',
    imageState: {
            src: 'http://localhost:3000/',
          },
        });

        $('.image-editor4').cropit({

     minZoom: 'fit',
    imageState: {
            src: 'http://localhost:3000/',
          },
        });




        $('.rotate-cw').click(function() {
          $('.image-editor1').cropit('rotateCW');
        });
        $('.rotate-ccw').click(function() {
          $('.image-editor1').cropit('rotateCCW');
        });



        $('.rotate-cw').click(function() {
          $('.image-editor2').cropit('rotateCW');
        });
        $('.rotate-ccw').click(function() {
          $('.image-editor2').cropit('rotateCCW');
        });



        $('.rotate-cw').click(function() {
          $('.image-editor3').cropit('rotateCW');
        });
        $('.rotate-ccw').click(function() {
          $('.image-editor3').cropit('rotateCCW');
        });



        $('.rotate-cw').click(function() {
          $('.image-editor4').cropit('rotateCW');
        });
        $('.rotate-ccw').click(function() {
          $('.image-editor4').cropit('rotateCCW');
        });









        var rangeInput = document.getElementById("exportav1");
        rangeInput.addEventListener('mouseup', function() {
          var imageData1 = $('.image-editor1').cropit('export');
       
          document.getElementById("medicine_avatar1_edit").value = imageData1;
          // window.open(imageData);

        });




        var rangeInput = document.getElementById("exportav2");
        rangeInput.addEventListener('mouseup', function() {
          var imageData2 = $('.image-editor2').cropit('export');
       
          document.getElementById("medicine_avatar2_edit").value = imageData2;
          // window.open(imageData);

        });


        var rangeInput = document.getElementById("exportav3");
        rangeInput.addEventListener('mouseup', function() {
          var imageData3 = $('.image-editor3').cropit('export');
       
          document.getElementById("medicine_avatar3_edit").value = imageData3;
          // window.open(imageData);

        });


        var rangeInput = document.getElementById("exportav4");
        rangeInput.addEventListener('mouseup', function() {
          var imageData4 = $('.image-editor4').cropit('export');
       
          document.getElementById("medicine_avatar4_edit").value = imageData4;
          // window.open(imageData);

        });




      });
    </script>

app/views/medicines/edit.html.erb
<div class="col-md-12"><br/>


  <div class="col-md-6"> 

    <div class="panel panel-default">
        <div class="panel-body">
            <h4>Edit Product medicines</h4>
            <hr/>
				<%= render 'form' %>

					
</div>

app/views/medicines/index.html.erb
  
  <h3 style="text-align:center;">
  unauthorized access
  </h3>


<style type="text/css">
  
#footer-area{
  display: none;
}

</style>

app/views/medicines/new.html.erb
<%= render 'layouts/defaultnav' %>

<div id="main-container" class="row">

		<%= render 'form' %>	

</div>

app/views/medicines/product_medicines.html.erb
	<%= render 'layouts/defaultnav' %>	

	<br/><div class="row" style="margin:10px;">
		<section class="products-list">		
	
						<!-- Heading Starts -->
							<h2 class="product-head">Medicine</h2>
						<!-- Heading Ends -->
						<!-- Products Row Starts -->
							<div class="row">
							<!-- Product #1 Starts -->
							<% @medicines.each do |medicine| %>
								<div class="col-md-2 col-sm-6">
									<div class="product-col">
										<div class="image">
											<% if !medicine.avatar1_file_name.nil?  %>
								                <%= image_tag medicine.avatar1.url, :id => "product_crop_image"  %>
								            <% else  %>      
												<img src="/assets/no_image.jpg" alt="product" class="img-responsive" />
								            <% end %>
										</div>
										<div class="caption">
											<h6>
											<%= link_to medicine.title, full_productinfo_medicines_path(:id => medicine) %>
											</h6>
											
											<div class="price">
												<span class="price-new"><%= medicine.price.to_i %> <%=t :MMK %></span> 
												<span class="price-old"><%= medicine.price.to_i + 15 %> <%=t :MMK %></span>
											</div>
											<div class="cart-button">
											
											<%= button_to line_items_path(:mmdealer_code => "medicines"+medicine.id.to_s, :user_id => medicine.user_id), :class =>"btn btn-cart" do %>
											     Add to cart &nbsp;&nbsp;
											  
											<% end %>


																			
											</div>
										</div>
									</div>
								</div>
							<% end %>
							<!-- Product #1 Ends -->
							<!-- Product #2 Starts -->
								
							<!-- Product #3 Ends -->
							</div>
						<!-- Products Row Ends -->
		</section>
	</div>
		</div>
	</div>
</div>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @medicine.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @medicine.category %>
</p>

<p>
  <strong>Certification:</strong>
  <%= @medicine.certification %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @medicine.ingredient %>
</p>

<p>
  <strong>Usage:</strong>
  <%= @medicine.usage %>
</p>

<p>
  <strong>Made by country:</strong>
  <%= @medicine.made_by_country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medicine.description %>
</p>

<p>
  <strong>Caution:</strong>
  <%= @medicine.caution %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>