config/routes.rb
Rails.application.routes.draw do
 
 
  resources :books
  resources :furnitures
  resources :seller_orders
  resources :hot_items
  resources :admins
  get 'admin_log_in' => "admins#admin_log_in", :as => :admin_log_in
  get 'admin_manage_personal_user' => "admins#admin_manage_personal_user", :as => :admin_manage_personal_user
  get 'admin_manage_retail_user' => "admins#admin_manage_retail_user", :as => :admin_manage_retail_user
  get 'admin_manage_company_user' => "admins#admin_manage_company_user", :as => :admin_manage_company_user
  get 'chat_to_seller' => "admins#chat_to_seller", :as => :chat_to_seller

  resources :comments
  resources :favourites
  resources :user_types

  devise_for :users, :authentication_token => 'authentication_token'
  put 'approve_seller/:id' => 'users#approve_seller', :as => :approve_seller
  put 'unapprove_seller/:id' => 'users#unapprove_seller', :as => :unapprove_seller

  namespace :myapi do
  namespace :v1 do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      post 'user_new' => 'registrations#user_new', :as => 'user_new'
      
    end
  end
end

  get 'buyer_sign_up' => 'users#buyer_sign_up', :as => :buyer_sign_up
  get 'seller_sign_up' => 'users#seller_sign_up', :as => :seller_sign_up

  get 'buyer_sign_in' => 'users#buyer_sign_in', :as => :buyer_sign_in
  get 'user_sign_in' => 'users#seller_sign_in', :as => :user_sign_in

  resources :users
  resources :buyer_reports
  get 'my_report' => 'buyer_reports#my_report'

  get 'admin_manage_shop' => 'admins#admin_manage_shop'
  get 'admin_manage_seller' => 'admins#admin_manage_seller'
  get 'admin_manage_buyer' => 'admins#admin_manage_buyer'
  get 'set_today_deal' => 'admins#set_today_deal'
  get 'admin_set_today_deal' => 'admins#admin_set_today_deal'
  get 'admin_manage_product' => 'admins#admin_manage_product'

   get 'admin_view_order_report' => 'admins#admin_view_order_report'
   get 'admin_view_product_report' => 'admins#admin_view_product_report'
   get 'admin_view_user_report' => 'admins#admin_view_user_report'

  resources :apis

  post 'open_new_store' => 'apis#open_new_store', :as => :open_new_store
  get 'seach_from_mobile' => 'apis#seach_from_mobile', :as => :seach_from_mobile
  post 'send_to_web' => 'apis#send_to_web', :as => 'send_to_web'
  get 'seller_buyer_conversation' => 'apis#seller_buyer_conversation', :as => :seller_buyer_conversation
  get 'set_order_status_by_seller' => 'apis#set_order_status_by_seller', :as => :set_order_status_by_seller
  get 'view_shop_licensce' => 'apis#view_shop_licensce', :as => :view_shop_licensce
  get 'order_view_by_seller' => 'apis#order_view_by_seller', :as => :order_view_by_seller
  get 'store_detail_view_by_seller' => 'apis#store_detail_view_by_seller', :as => :store_detail_view_by_seller
  get 'store_detail_view_by_buyer' => 'apis#store_detail_view_by_buyer', :as => :store_detail_view_by_buyer

  get 'my_product_order_list' => 'apis#my_product_order_list', :as => :my_product_order_list
  post 'edit_my_store' => 'apis#edit_my_store', :as => :edit_my_store
  post 'edit_my_product' => 'apis#edit_my_product', :as => :edit_my_product
  get 'order_confirm_list' => 'apis#order_confirm_list', :as => :order_confirm_list
  get 'order_delivery_list' => 'apis#order_delivery_list', :as => :order_delivery_list
  get 'order_completed_list' => 'apis#order_completed_list', :as => :order_completed_list
  get 'order_rejected_list' => 'apis#order_rejected_list', :as => :order_rejected_list
  get 'order_processing_list' => 'apis#order_processing_list', :as => :order_processing_list

  post 'to_send_shipment' => 'apis#to_send_shipment', :as => :to_send_shipment
  get 'store_desc' => 'apis#store_desc', :as => :store_desc
  get 'last_three_json' => 'apis#last_three_json', :as => :last_three_json

  get 'get_store_product' => "apis#get_store_product", :as => :get_store_product
  get 'get_store_product_by_seller' => "apis#get_store_product_by_seller", :as => :get_store_product_by_seller

  post 'to_send_rating' => "apis#to_send_rating", :as => :to_send_rating
  get 'get_rating' => "apis#get_rating", :as => :get_rating

  get 'test_json' => 'apis#test_json', :as => :test_json
  get 'my_big_deals' => 'apis#my_big_deals', :as => :my_big_deals
  get 'my_api_services' => 'apis#my_api_services', :as => :my_api_services
  get 'my_api_training_and_schools' => 'apis#my_api_training_and_schools', :as => :my_api_training_and_schools
  get 'my_api_sports' => 'apis#my_api_sports', :as => :my_api_sports
  get 'my_api_toys' => 'apis#my_api_toys', :as => :my_api_toys
  get 'my_api_gifts' => 'apis#my_api_gifts', :as => :my_api_gifts
  get 'my_api_car_accessories' => 'apis#my_api_car_accessories', :as => :my_api_car_accessories
  get 'my_api_motorcycle_accessories' => 'apis#my_api_motorcycle_accessories', :as => :my_api_motorcycle_accessories
  get 'my_api_machines' => 'apis#my_api_machines', :as => :my_api_machines
  get 'my_api_instruments' => 'apis#my_api_instruments', :as => :my_api_instruments
  get 'my_api_equipment' => 'apis#my_api_equipment', :as => :my_api_equipment
  get 'my_api_bath_supplies' => 'apis#my_api_bath_supplies', :as => :my_api_bath_supplies
  get 'my_api_makeup_and_skincares' => 'apis#my_api_makeup_and_skincares', :as => :my_api_makeup_and_skincares
  get 'my_api_beauty_equipments' => 'apis#my_api_beauty_equipments', :as => :my_api_beauty_equipments
  get 'my_api_medicines' => 'apis#my_api_medicines', :as => :my_api_medicines
  get 'my_api_home_appliances' => 'apis#my_api_home_appliances', :as => :my_api_home_appliances
  get 'my_api_computers' => 'apis#my_api_computers', :as => :my_api_computers
  get 'my_api_telephone_accessories' => 'apis#my_api_telephone_accessories', :as => :my_api_telephone_accessories
  get 'my_api_electrical_equipments' => 'apis#my_api_electrical_equipments', :as => :my_api_electrical_equipments
  get 'my_api_fashion_hats' => 'apis#my_api_fashion_hats', :as => :my_api_fashion_hats
  get 'my_api_fashion_footwears' => 'apis#my_api_fashion_footwears', :as => :my_api_fashion_footwears
  get 'my_api_fashion_bags' => 'apis#my_api_fashion_bags', :as => :my_api_fashion_bags
  get 'my_api_fashion_accessories' => 'apis#my_api_fashion_accessories', :as => :my_api_fashion_accessories
  get 'my_api_fashion_clothings' => 'apis#my_api_fashion_clothings', :as => :my_api_fashion_clothings
  get 'my_api_stores' => 'apis#my_api_stores', :as => :my_api_stores
  post 'get_ip' => 'apis#get_ip', :as => :get_ip

  

  resources :services
  resources :training_and_schools
  resources :sports
  resources :toys
  resources :gifts
  resources :car_accessories
  resources :motorcycle_accessories
  resources :machines
  resources :instruments
  resources :equipment
  resources :bath_supplies
  resources :makeup_and_skincares
  resources :beauty_equipments
  resources :medicines
  resources :home_appliances
  resources :computers
  resources :telephone_accessories
  resources :telephone_accessories
  resources :electrical_equipments
  resources :fashion_hats
  resources :fashion_footwears
  resources :fashion_bags
  resources :fashion_accessories
  resources :fashion_clothings
  resources :carts
  get 'add_to_cart' => 'carts#_cart'

  resources :line_items
  get 'my_items' => 'line_items#my_items'
  

  resources :orders
  get 'my_order' => 'orders#my_order'
  get 'my_order_status' => 'orders#my_order_status'

  resources :products
  get 'my_product' => 'products#my_product', :as => :my_product
  get 'my_products' => 'products#my_products', :as => :my_products
  get 'my_sell_product' => 'products#my_sell_product', :as => :my_sell_product
  get 'set_as_bigdeal/:id' => 'products#set_as_bigdeal', :as => :set_as_bigdeal
  

  resources :stores
  get 'dashboard' => 'stores#dashboard', :as => :dashboard

  resources :fashions
  resources :fronts

  get "big_deals" => "fronts#big_deals", :as => :big_deals  

  get "products_by_category" => "fronts#products_by_category", :as => :products_by_category
  get "apply_as_seller/:id" => "fronts#apply_as_seller", :as => :apply_as_seller
  get "unauthorized" => "fronts#unauthorized", :as => :unauthorized
  get "send_to_pusher" => "fronts#send_to_pusher", :as => :send_to_pusher
  get "add_to_favourite" => "fronts#add_to_favourite", :as => :add_to_favourite
  get "search_result" => "fronts#search_result", :as => :search_result
  root 'fronts#home'

 get 'home' => 'fronts#home'
 get 'about' => 'fronts#about'
 get 'cart' => 'fronts#cart'
 get 'category' => 'fronts#category'
 get 'category_list' => 'fronts#category_list'
 get 'compare' => 'fronts#compare'
 get 'contact' => 'fronts#contact'
 get 'login' => 'fronts#login'
 get 'product' => 'fronts#product'
 get 'product_full' => 'fronts#product_full' , :as => :product_full
 get 'mobile_product_detail' => 'fronts#mobile_product_detail' , :as => :mobile_product_detail

 get 'register' => 'fronts#register'
 get 'check_out' => 'fronts#check_out'
 get 'thanks_you' => 'fronts#thanks_you'
 get 'check_out_as_guest' => 'fronts#check_out_as_guest'
 get 'product_by_category' => 'fronts#product_by_category'
 get 'my_conversation' => 'fronts#my_conversation'
 
 

 get 'fashion_related' => 'fronts#fashion_related', :as => :fashion_related
 get 'electronics_related' => 'fronts#electronics_related', :as => :electronics_related
 get 'health_beauty_related' => 'fronts#health_beauty_related', :as => :health_beauty_related
 get 'industrial_part' => 'fronts#industrial_part', :as => :industrial_part
 get 'auto_transportation' => 'fronts#auto_transportation', :as => :auto_transportation
 get 'sports_related' => 'fronts#sports_related', :as => :sports_related
 get 'service_related' => 'fronts#service_related', :as => :service_related

 get 'product_bath_supplies' => 'bath_supplies#product_bath_supplies', :as => :product_bath_supplies
  

app/models/store.rb
class Store < ActiveRecord::Base


  belongs_to :seller


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  layout :layout_per_action

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  def dashboard

  end


  # GET /stores/1
  # GET /stores/1.json
  def show
   
      @products = Product.where(:user_id => current_user.id)
      @raw_store_id = Store.where(:user_id => current_user.id).pluck(:id)
      @store_id = @raw_store_id.to_s.gsub("[", "").gsub("]", "")
      @users = User.all

      redirect_to "/not_approve_sorry", error: 'You dont have enough permissions to be here' unless current_user.admin_approved == "t"
      return true

  end

  # GET /stores/new
  def new
    @store = Store.new
    redirect_to "/not_approve_sorry", error: 'You dont have enough permissions to be here' unless current_user.admin_approved == "t"
    return true
    
  end

  # GET /stores/1/edit
  def edit
    @raw_store_id = Store.where(:user_id => current_user.id).pluck(:id)
      @store_id = @raw_store_id.to_s.gsub("[", "").gsub("]", "")
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
         @seller = User.find(current_user.id)
         @seller.update(:has_store => "yes")

        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to request.env['HTTP_REFERER'], notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:description_image1,:description_image2,:description_image3,:description_image4,:term, :ads_one, :ads_two, :user_id,:avatar, :store_name, :store_address, :store_contact, :description, :user_id, :seller_name)
    end

    def layout_per_action
      if action_name == "index"
           "application"
      elsif action_name == "new" || action_name == "edit"
           "application"
      else
        "backend"
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_name %><br>
    <%= f.text_field :store_name %>
  </div>
  <div class="field">
    <%= f.label :store_address %><br>
    <%= f.text_field :store_address %>
  </div>
  <div class="field">
    <%= f.label :store_contact %><br>
    <%= f.text_field :store_contact %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id%>
  </div>
  <div class="field">
    <%= f.label :seller_name %><br>
    <%= f.text_field :seller_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/dashboard.html.erb
aok

app/views/stores/index.html.erb
  
  <h3 style="text-align:center;">
  unauthorized access
  </h3>


<style type="text/css">
  
#footer-area{
  display: none;
}

</style>

app/views/stores/show.html.erb
<div class="col-md-12">
  <div class="col-md-3">


        <div class="panel panel-default">
          <div class="panel-body">
          <center>
           
             <% if !@store.avatar.nil?  %>
                    <%= image_tag @store.avatar, :id => "store_avatar" %>
              <% else  %>      
                   <%= image_tag "shop-icon.png", :id => "store_avatar" %>
            <% end %>
          </center> 
          <br/>
           
          </div>
        </div>


  </div>

  <div class="col-md-5">


        <div class="panel panel-default">
          <div class="panel-body">

           
            About store
            <hr/>
            <%= @store.description %>
          </div>
        </div>


  </div>
  <div class="col-md-4">
    
            <ul class="list-group">
                <li class="list-group-item">Store: 
                <span style="color:grey;"><%= @store.store_name %></span></li>
               
                <li class="list-group-item">Address: 
                 <span style="color:grey;"><%= @store.store_address %></span></li>
          
                <li class="list-group-item">Contact: 
                 <span style="color:grey;"><%= @store.store_contact %>
                 </span></li>

          
               
                <li class="list-group-item">Seller:
                 <span style="color:grey;"> <%= @store.seller_name %>
                 </span></li>

                 <li class="list-group-item">
                 <%= link_to 'edit store profile here', edit_store_path(@store) %>
                 </li>
            </ul>
        
  </div>




<div class="col-md-12">

      <div class="well well-lg"> Store Images</div>

      <img src="<%= @store.description_image1 %>" id="desc_image"/>
      <img src="<%= @store.description_image2 %>" id="desc_image"/>
      <img src="<%= @store.description_image3 %>" id="desc_image"/>
      <img src="<%= @store.description_image4 %>" id="desc_image"/>


  <div class="well well-lg"> Store Cover</div>
       <img src="<%= @store.ads_one %>" id="desc_image"/><br/>
       <img src="<%= @store.ads_two %>" id="desc_image"/><br/>



<div class="page-header">
  <h3>Products <small> (Upload your products to your online store)</small></h3>

  <div class="bs-example" data-example-id="contextual-panels">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Add fashion related products to your store</h3>
      </div>
      <div class="panel-body">
                <a href="/fashion_clothings/new" class="btn btn-default">Clothings</a>
                <a href="/fashion_hats/new" class="btn btn-default">Hats</a>
                <a href="/fashion_footwears/new" class="btn btn-default">Footwears</a>
                <a href="/fashion_bags/new" class="btn btn-default">Bags</a>
                <a href="/fashion_accessories/new" class="btn btn-default">Accessories</a>
      </div>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Add electronics</h3>
      </div>
      <div class="panel-body">
                <a href="/electrical_equipments/new" class="btn btn-default">Electrical Equipments</a>
                <a href="/telephone_accessories/new" class="btn btn-default">Telephone and Accessories</a>
                <a href="/computers/new" class="btn btn-default">Computers and Laptops</a>
                <a href="/home_appliances/new" class="btn btn-default">Home Appliance </a>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Health & Beauty</h3>
      </div>
      <div class="panel-body">
                  <a href="/medicines/new" class="btn btn-default">Medicine </a>
                  <a href="/beauty_equipments/new" class="btn btn-default">Beauty Equipments </a>
                  <a href="/makeup_and_skincares/new" class="btn btn-default">Makeup and Skincare </a>
                  <a href="/bath_supplies/new" class="btn btn-default">Bath supply </a>
      </div>
    </div>
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Industrial Parts Tools</h3>
      </div>
      <div class="panel-body">
              
                  <a href="/equipment/new" class="btn btn-default">Industrial Equipments </a>
                  <a href="/instruments/new" class="btn btn-default">Instruments </a>
                  <a href="/machines/new" class="btn btn-default">Machines </a>
                  <a href="/furnitures/new" class="btn btn-default">Furnitures </a>
      </div>
    </div>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Auto Transportation</h3>
      </div>
      <div class="panel-body">
                 <a href="/motorcycle_accessories/new" class="btn btn-default">Motorcycle Accessories </a>
                 <a href="/car_accessories/new" class="btn btn-default">Motorcar Accessories </a>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Gifts</h3>
      </div>
      <div class="panel-body">
               <a href="/gifts/new" class="btn btn-default">Special Gifts </a>
               <a href="/sports/new" class="btn btn-default">Sports Accessories </a>
               <a href="/toys/new" class="btn btn-default" >Toys </a>
               <a href="/books/new" class="btn btn-default" >Books </a>

      </div>
    </div>

  </div>
  <div ng-app="plunker">
   <div ng-controller="MainCtrl">

             <div class="panel panel-default">
                  <div class="panel-heading">
                     Add as my seller
                  </div>
                  <div class="panel-body">
                     <div class="row">
                        <div class="col-lg-12">
                          
                           <div ng-init="users = <%= @users.to_json %>">
                           </div>
                           <!-- filter with name -->
                       
                              <input  ng-model="user.name" type="text" class="form-control input-lg" placeholder="Search by their name">
                           <br/>
                           <table class="table table-bordered">
                              <thead>
                                 <tr>
                                    <th>Name</th>
                                    <th colspan="2"></th>
                                 </tr>
                              </thead>
                              <tbody>
                                 <tr ng-repeat="user in users | filter:{name:  user.name}">
                                    <td>{{user.name}}</td>
                                    <td> 
                                       <a id="set_admin" class="btn btn-warning btn-sm" 
                                       href="/set_my_seller?id={{user.id}}&store_id=<%= @store.id %>" data-remote=true  >


                                       Set us my seller</a>


                                    </td>
                                 </tr>
                              </tbody>
                           </table>
                        </div>
                     </div>
                     <!-- /.row (nested) -->
                  </div>
                  <!-- /.panel-body -->
               </div>
        </div>
  </div>


  </div>




</div>


<br>


</div>

</div>





 

<script type="text/javascript">
  

          
    $('#set_admin').on('click', function () {
       
       alert("set as your seller DONE");
    });


</script>