config/routes.rb
Rails.application.routes.draw do
 
 
  resources :books
  resources :furnitures
  resources :seller_orders
  resources :hot_items
  resources :admins
  get 'admin_log_in' => "admins#admin_log_in", :as => :admin_log_in
  get 'admin_manage_personal_user' => "admins#admin_manage_personal_user", :as => :admin_manage_personal_user
  get 'admin_manage_retail_user' => "admins#admin_manage_retail_user", :as => :admin_manage_retail_user
  get 'admin_manage_company_user' => "admins#admin_manage_company_user", :as => :admin_manage_company_user
  get 'chat_to_seller' => "admins#chat_to_seller", :as => :chat_to_seller

  resources :comments
  resources :favourites
  resources :user_types

  devise_for :users, :authentication_token => 'authentication_token'
  put 'approve_seller/:id' => 'users#approve_seller', :as => :approve_seller
  put 'unapprove_seller/:id' => 'users#unapprove_seller', :as => :unapprove_seller

  namespace :myapi do
  namespace :v1 do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      post 'user_new' => 'registrations#user_new', :as => 'user_new'
      
    end
  end
end

  get 'buyer_sign_up' => 'users#buyer_sign_up', :as => :buyer_sign_up
  get 'seller_sign_up' => 'users#seller_sign_up', :as => :seller_sign_up

  get 'buyer_sign_in' => 'users#buyer_sign_in', :as => :buyer_sign_in
  get 'user_sign_in' => 'users#seller_sign_in', :as => :user_sign_in

  resources :users
  resources :buyer_reports
  get 'my_report' => 'buyer_reports#my_report'

  get 'admin_manage_shop' => 'admins#admin_manage_shop'
  get 'admin_manage_seller' => 'admins#admin_manage_seller'
  get 'admin_manage_buyer' => 'admins#admin_manage_buyer'
  get 'set_today_deal' => 'admins#set_today_deal'
  get 'admin_set_today_deal' => 'admins#admin_set_today_deal'
  get 'admin_manage_product' => 'admins#admin_manage_product'

   get 'admin_view_order_report' => 'admins#admin_view_order_report'
   get 'admin_view_product_report' => 'admins#admin_view_product_report'
   get 'admin_view_user_report' => 'admins#admin_view_user_report'

  resources :apis

  post 'open_new_store' => 'apis#open_new_store', :as => :open_new_store
  get 'seach_from_mobile' => 'apis#seach_from_mobile', :as => :seach_from_mobile
  post 'send_to_web' => 'apis#send_to_web', :as => 'send_to_web'
  get 'seller_buyer_conversation' => 'apis#seller_buyer_conversation', :as => :seller_buyer_conversation
  get 'set_order_status_by_seller' => 'apis#set_order_status_by_seller', :as => :set_order_status_by_seller
  get 'view_shop_licensce' => 'apis#view_shop_licensce', :as => :view_shop_licensce
  get 'order_view_by_seller' => 'apis#order_view_by_seller', :as => :order_view_by_seller
  get 'store_detail_view_by_seller' => 'apis#store_detail_view_by_seller', :as => :store_detail_view_by_seller
  get 'store_detail_view_by_buyer' => 'apis#store_detail_view_by_buyer', :as => :store_detail_view_by_buyer

  get 'my_product_order_list' => 'apis#my_product_order_list', :as => :my_product_order_list
  post 'edit_my_store' => 'apis#edit_my_store', :as => :edit_my_store
  post 'edit_my_product' => 'apis#edit_my_product', :as => :edit_my_product
  get 'order_confirm_list' => 'apis#order_confirm_list', :as => :order_confirm_list
  get 'order_delivery_list' => 'apis#order_delivery_list', :as => :order_delivery_list
  get 'order_completed_list' => 'apis#order_completed_list', :as => :order_completed_list
  get 'order_rejected_list' => 'apis#order_rejected_list', :as => :order_rejected_list
  get 'order_processing_list' => 'apis#order_processing_list', :as => :order_processing_list

  post 'to_send_shipment' => 'apis#to_send_shipment', :as => :to_send_shipment
  get 'store_desc' => 'apis#store_desc', :as => :store_desc
  get 'last_three_json' => 'apis#last_three_json', :as => :last_three_json

  get 'get_store_product' => "apis#get_store_product", :as => :get_store_product
  get 'get_store_product_by_seller' => "apis#get_store_product_by_seller", :as => :get_store_product_by_seller

  post 'to_send_rating' => "apis#to_send_rating", :as => :to_send_rating
  get 'get_rating' => "apis#get_rating", :as => :get_rating

  get 'test_json' => 'apis#test_json', :as => :test_json
  get 'my_big_deals' => 'apis#my_big_deals', :as => :my_big_deals
  get 'my_api_services' => 'apis#my_api_services', :as => :my_api_services
  get 'my_api_training_and_schools' => 'apis#my_api_training_and_schools', :as => :my_api_training_and_schools
  get 'my_api_sports' => 'apis#my_api_sports', :as => :my_api_sports
  get 'my_api_toys' => 'apis#my_api_toys', :as => :my_api_toys
  get 'my_api_gifts' => 'apis#my_api_gifts', :as => :my_api_gifts
  get 'my_api_car_accessories' => 'apis#my_api_car_accessories', :as => :my_api_car_accessories
  get 'my_api_motorcycle_accessories' => 'apis#my_api_motorcycle_accessories', :as => :my_api_motorcycle_accessories
  get 'my_api_machines' => 'apis#my_api_machines', :as => :my_api_machines
  get 'my_api_instruments' => 'apis#my_api_instruments', :as => :my_api_instruments
  get 'my_api_equipment' => 'apis#my_api_equipment', :as => :my_api_equipment
  get 'my_api_bath_supplies' => 'apis#my_api_bath_supplies', :as => :my_api_bath_supplies
  get 'my_api_makeup_and_skincares' => 'apis#my_api_makeup_and_skincares', :as => :my_api_makeup_and_skincares
  get 'my_api_beauty_equipments' => 'apis#my_api_beauty_equipments', :as => :my_api_beauty_equipments
  get 'my_api_medicines' => 'apis#my_api_medicines', :as => :my_api_medicines
  get 'my_api_home_appliances' => 'apis#my_api_home_appliances', :as => :my_api_home_appliances
  get 'my_api_computers' => 'apis#my_api_computers', :as => :my_api_computers
  get 'my_api_telephone_accessories' => 'apis#my_api_telephone_accessories', :as => :my_api_telephone_accessories
  get 'my_api_electrical_equipments' => 'apis#my_api_electrical_equipments', :as => :my_api_electrical_equipments
  get 'my_api_fashion_hats' => 'apis#my_api_fashion_hats', :as => :my_api_fashion_hats
  get 'my_api_fashion_footwears' => 'apis#my_api_fashion_footwears', :as => :my_api_fashion_footwears
  get 'my_api_fashion_bags' => 'apis#my_api_fashion_bags', :as => :my_api_fashion_bags
  get 'my_api_fashion_accessories' => 'apis#my_api_fashion_accessories', :as => :my_api_fashion_accessories
  get 'my_api_fashion_clothings' => 'apis#my_api_fashion_clothings', :as => :my_api_fashion_clothings
  get 'my_api_stores' => 'apis#my_api_stores', :as => :my_api_stores
  post 'get_ip' => 'apis#get_ip', :as => :get_ip

  

  resources :services
  resources :training_and_schools
  resources :sports
  resources :toys
  resources :gifts
  resources :car_accessories
  resources :motorcycle_accessories
  resources :machines
  resources :instruments
  resources :equipment
  resources :bath_supplies
  resources :makeup_and_skincares
  resources :beauty_equipments
  resources :medicines
  resources :home_appliances
  resources :computers
  resources :telephone_accessories
  resources :telephone_accessories
  resources :electrical_equipments
  resources :fashion_hats
  resources :fashion_footwears
  resources :fashion_bags
  resources :fashion_accessories
  resources :fashion_clothings
  resources :carts
  get 'add_to_cart' => 'carts#_cart'

  resources :line_items
  get 'my_items' => 'line_items#my_items'
  

  resources :orders
  get 'my_order' => 'orders#my_order'
  get 'my_order_status' => 'orders#my_order_status'

  resources :products
  get 'my_product' => 'products#my_product', :as => :my_product
  get 'my_products' => 'products#my_products', :as => :my_products
  get 'my_sell_product' => 'products#my_sell_product', :as => :my_sell_product
  get 'set_as_bigdeal/:id' => 'products#set_as_bigdeal', :as => :set_as_bigdeal
  

  resources :stores
  get 'dashboard' => 'stores#dashboard', :as => :dashboard

  resources :fashions
  resources :fronts

  get "big_deals" => "fronts#big_deals", :as => :big_deals  

  get "products_by_category" => "fronts#products_by_category", :as => :products_by_category
  get "apply_as_seller/:id" => "fronts#apply_as_seller", :as => :apply_as_seller
  get "unauthorized" => "fronts#unauthorized", :as => :unauthorized
  get "send_to_pusher" => "fronts#send_to_pusher", :as => :send_to_pusher
  get "add_to_favourite" => "fronts#add_to_favourite", :as => :add_to_favourite
  get "search_result" => "fronts#search_result", :as => :search_result
  root 'fronts#home'

 get 'home' => 'fronts#home'
 get 'about' => 'fronts#about'
 get 'cart' => 'fronts#cart'
 get 'category' => 'fronts#category'
 get 'category_list' => 'fronts#category_list'
 get 'compare' => 'fronts#compare'
 get 'contact' => 'fronts#contact'
 get 'login' => 'fronts#login'
 get 'product' => 'fronts#product'
 get 'product_full' => 'fronts#product_full' , :as => :product_full
 get 'mobile_product_detail' => 'fronts#mobile_product_detail' , :as => :mobile_product_detail

 get 'register' => 'fronts#register'
 get 'check_out' => 'fronts#check_out'
 get 'thanks_you' => 'fronts#thanks_you'
 get 'check_out_as_guest' => 'fronts#check_out_as_guest'
 get 'product_by_category' => 'fronts#product_by_category'
 get 'my_conversation' => 'fronts#my_conversation'
 
 

 get 'fashion_related' => 'fronts#fashion_related', :as => :fashion_related
 get 'electronics_related' => 'fronts#electronics_related', :as => :electronics_related
 get 'health_beauty_related' => 'fronts#health_beauty_related', :as => :health_beauty_related
 get 'industrial_part' => 'fronts#industrial_part', :as => :industrial_part
 get 'auto_transportation' => 'fronts#auto_transportation', :as => :auto_transportation
 get 'sports_related' => 'fronts#sports_related', :as => :sports_related
 get 'service_related' => 'fronts#service_related', :as => :service_related

 get 'product_bath_supplies' => 'bath_supplies#product_bath_supplies', :as => :product_bath_supplies
  

app/models/line_item.rb
class LineItem < ActiveRecord::Base


	
	
	belongs_to :product
	belongs_to :cart

	def total_price
		product.price.to_i * quantity
	end

	

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  layout :layout_per_action
  # GET /line_items
  # GET /line_items.json
  def index
    
      if params[:cart_id]
         @line_items = LineItem.where("cart_id = ? ", params[:cart_id]).where(:user_id => current_user.id)
      end
   
        @raw_store_id = Store.where(:user_id => current_user.id).pluck(:id)
     @store_id = @raw_store_id.to_s.gsub("[", "").gsub("]", "")
  end


  def my_items
    
      if params[:cart_id]
         @line_items = LineItem.where("cart_id = ? ", params[:cart_id])
      end
   
     
  end





  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def referer
    @env['HTTP_REFERER'] || '/'
  end

  def create
      @cart = current_cart
     
      product = Product.where("mmdealer_code = ?", params[:mmdealer_code]).ids
      @product_id = product.to_s.gsub("[","")
     
      user = User.find(params[:user_id])
      @line_item = @cart.add_item(@product_id,user.id)
      respond_to do |format|
            if @line_item.save
              format.html { redirect_to request.referer }
              format.xml { render :xml => @line_item, :status => :created, :location => @line_item }
            else
              format.html { render :action => "new" }
              format.xml { render :xml => @line_item.errors, :status => :unprocessable_entity }
            end
        end
   end


  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to check_out_path, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id, :user_id, :product_name)
    end

    def layout_per_action
      if action_name == "index"
           "backend"
      elsif action_name == "my_items"
           "application"
      else
           "application"
      end
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_cart_item.html.erb
                  <table class="table hcart">

                    <tr>
                      <td class="text-center">
                        <a href="#">
                         <img src="/assets/product-images/hcart-thumb1.jpg" alt="image" title="image" class="img-thumbnail img-responsive" />
                        </a>
                      </td>
                      <td class="text-left">
                        <a href="#">
                          <%= line_item.product.title %>
                        </a>
                      </td>
                      <td class="text-right">x <%= line_item.quantity %></td>
                      <td class="text-right"><%= (line_item.total_price) %> MMK</td>
                    </tr>
                   
                  </table>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
   <% if !request.original_url.include? "check_out" %>
                  <table class="table hcart">

                    <tr>
                      <td class="text-center">
                        <a href="#">
                          <%= image_tag line_item.product.avatar1_edit, :style=>"height:300px;width:300px;" %>
                        </a>
                      </td>
                      <td class="text-left">
                        <a href="#">
                          <%= line_item.product.title %>
                        </a>
                      </td>
                      <td class="text-right">x <%= line_item.quantity %></td>
                      <td class="text-right"><%= (line_item.total_price) %> MMK</td>
                    </tr>
                   
                  </table>


<% elsif request.original_url.include? "check_out" %>

          <tr>
            <td class="text-center">
              <a href="#">

                  <%= image_tag line_item.product.avatar1_edit, :style=>"height:300px;width:300px;" %>
              </a>
            </td>
            <td class="text-center">
              <a href="#"><%= line_item.product.title %></a>
            </td>             
            <td class="text-center">
              <div class="input-group btn-block">
                <input type="text" name="quantity" value="<%= line_item.quantity %>" size="1" class="form-control" disabled />
              </div>                
            </td>
            <td class="text-center">
              <%= line_item.product.price %>
            </td>
            <td class="text-center">
              <%= line_item.product.price * line_item.quantity %>
            </td>
            <td class="text-center">
              
              <%= link_to 'remove', line_item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"  %>
            </td>
          </tr>


<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<div class="col-md-12">
<div class="panel panel-default">
  <div class="panel-body">
     <p>MyCustomer order details</p>
     <hr/>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
            </tr>
          </thead>

          <tbody>
            <% @line_items.each do |line_item| %>
              <tr>
                <td><%= line_item.product.title %></td>
                <td><%= line_item.quantity %></td>
               
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>
</div>

app/views/line_items/line_items.htm.erb
<div class="col-md-12">
<div class="panel panel-default">
  <div class="panel-body">
     <p>MyCustomer order details</p>
     <hr/>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
            </tr>
          </thead>

          <tbody>
            <% @line_items.each do |line_item| %>
              <tr>
                <td><%= line_item.product.title %></td>
                <td><%= line_item.quantity %></td>
               
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>
</div>

app/views/line_items/my_items.html.erb
<%= render 'layouts/defaultnav' %>  


<div id="main-container" class="container">

<br/><br/>

<div class="col-md-12">
<div class="panel panel-default">
  <div class="panel-body">
     <p>MyOrder details</p>
     <a class="btn btn-default" href="/my_order" role="button">back to order list</a>
     <hr/>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
            </tr>
          </thead>

          <tbody>
            <% @line_items.each do |line_item| %>
              <tr>
                <td><%= line_item.product.title %></td>
                <td><%= line_item.quantity %></td>
               
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>
</div>

</div>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>